@startuml
'https://plantuml.com/class-diagram

class Streaming
class MediaHandler{
- Media currentMedia
- IO io
- ArrayList<Media> media
+ MediaHandler(IO)
+ Media getCurrentMedia()
+ ArrayList<Media> getListFromInline(String)
+ ArrayList<Media> getMedia()
+ Media getMediaFromName(String)
+ String inlineListString(ArrayList<Media>)
+ void loadMovies()
+ void loadSeries()
+ ArrayList<Media> searchGenre(String)
+ ArrayList<Media> searchMedia(String,String,String,float,float)
+ ArrayList<Media> searchMedia(ArrayList<Media>,String,String,float,float)
+ ArrayList<Media> searchName(String)
+ ArrayList<Media> searchRating(float,float)
+ ArrayList<Media> searchYear(String)
+ void selectMedia(Media)
+ void selectMedia(String)
}
abstract class Media{
- String Genre
- String name
- float rating
- String year
+ Media(String,String,float,String)
+ String getGenre()
+ String getName()
+ float getRating()
+ String getYear()
+ String toString()
}
class Movie{
- double lengthOfMovie
+ Movie(String,String,float,String,double)
+ double getLengthOfMovie()
+ String toString()
}
class Series{
- ArrayList<Interger> episodes
+ Series(String,String,float,double,String,ArrayList<Interger>)
+ String toString()
}
class UserHandler{
# ArrayList<User> users
# User currentUser
- IO io
+ UserHandler(IO,MediaHandler)
+ void changeUsername(String) throws InvalidUsername
+ boolean currentUserIsAdmin()
+ boolean currentUserIsAdult()
+ User getCurrentUser()
+ User getUser(int)
+ ArrayList<User> getUsers()
+ boolean hasCurrrentUser()
+ void login(String,String)
+ void registerUser(String,String,boolean)
+ void save()
+ void setCurrentUser(User)
}
class User{
- String username
- String password
- FINAL int id
- int countID
- boolean isAdmin
- boolean isAdult
- ArrayList<Media> savedMedia
- ArrayList<Media> watchedMedia
+ User(String,String,boolean,boolean)
+ User(String,String,boolean,boolean,ArrayList<Media>)
+ void addSavedMedia(Media)
+ void addWatchedMedia(Media)
+ int getId()
+ String getPassword()
+ ArrayList<Media> getSavedMedia()
+ String getUsername()
+ ArrayList<Media> getWatchedMedia()
+ boolean isAdmin
+ boolean isAdult
+ void removeSavedMedia(Media)
+ String saveUserData()
+ void setUsername(String)
+ String toString()
}
class FileIO
interface IO
interface UI
class TextUI
class ExceptionHandler



Streaming *-- UserHandler
UserHandler *-- User
Streaming *-- MediaHandler
MediaHandler *-- Media
Media <|--  Movie
Media <|--  Series

IO <|-- "implements" FileIO
UI <|-- "implements" TextUI
ExceptionHandler *-- UI
ExceptionHandler <|-- inValidPasswordException
ExceptionHandler <|-- inValidUsername
ExceptionHandler <|-- inValidPasswordOrPasswordException
Streaming *-- ExceptionHandler
UserHandler *-- IO
MediaHandler *-- IO
'''Streaming *-- IO
Streaming *-- UI

Streaming : - UserHandler userHandler
Streaming : - MediaHandler mediaHandler
Streaming : - UI ui
'''Streaming : - IO io
Streaming : + void dataSetup()
Streaming : + void mainMenu()
Streaming : + void exit()

TextUI : - Scanner scan
TextUI : + String getUserInput(String msg)
TextUI : + String displayMsg(String msg)
TextUI : + void printMenu(boolean isAdult, boolean isAdmin)
TextUI : - ExceptionHandler exceptionHandler


IO : + ArrayList<String> readDataMedia() throws FileNotFoundException
IO : + ArrayList<String> readDataSeries() throws IOException
IO : + ArrayList<String> readDataUser(User currentUser) throws IOException
IO : + void writeDataUser(User currentUser)

UI : + void login()
UI : + void loginOrRegister()
UI : + void registerUser()
UI : + void library()
UI : + void viewMovie()

FileIO : - ArrayList<String> read(String)



@enduml