@startuml
'https://plantuml.com/class-diagram

class Streaming
class MediaHandler
abstract class Media
class Movie
class Series
class UserHandler
class FileIO
interface IO
interface UI
class TextUI
class ExceptionHandler
class User



Streaming *-- UserHandler
UserHandler *-- User
Streaming *-- MediaHandler
MediaHandler *-- Media
Media <|--  Movie
Media <|--  Series

IO <|-- "implements" FileIO
UI <|-- "implements" TextUI
TextUI *-- ExceptionHandler
Streaming *-- IO
Streaming *-- UI

UserHandler : + ArrayList<User> getUsers()
UserHandler : - void setCurrentUser()
UserHandler : + User getCurrentUser()
UserHandler : - ArrayList<User> users
UserHandler : - User currentUser
UserHandler : + void login(User user)
UserHandler : + User registerUser(String name, String password, boolean isAdult)
UserHandler : - boolean isValidUsername()
UserHandler : - boolean isValidPassword()
UserHandler : + boolean currentUserIsAdult()
UserHandler : + boolean currentUserIsAdmin()

User : - boolean isAdult
User : - String username
User : - FINAL int id
User : - boolean isAdmin
User : - ArrayList<Media> savedMedia
User : - ArrayList<Media> watchedMedia
User : + User(String username, String password, boolean isAdult, boolean isAdmin)
User : + void setUsername()
User : + String getUsername()
User : + int getId()
User : + ArrayList<Media> getWatchedMedia()
User : + ArrayList<Media> getSavedMedia()
User : + boolean getIsAdmin()
User : + boolean getIsAdult()

MediaHandler : +MediaHandler(currentUser)
MediaHandler : - List<Media> media
MediaHandler : + playMedia(media)

Streaming : -UserHandler userHandler
Streaming : -MediaHandler mediaHandler
Streaming : - UI ui
Streaming : - IO io
Streaming : + void Datasetup()
Streaming : + void Mainmenu()
Streaming : + void Exit()

TextUI : - Scanner scan
TextUI : + String getUserInput(String msg)
TextUI : + String displayMsg(String msg)
TextUI : + void printMenu(boolean isAdult, boolean isAdmin)
TextUI : - ExceptionHandler exceptionHandler


IO : + List readDataMedia()
IO : + List readDataUser(User currentUser)
IO : + void writeData(User currentUser)

FileIO : - Scanner scan
FileIO : - File file
FileIO : + void readData(File file)
FileIO : + void writeData(User currentUser)

MediaHandler : - ArrayList searchGenre(String)
MediaHandler : - ArrayList searchName(String)
MediaHandler : - ArrayList searchYear(String)
MediaHandler : - ArrayList searchRating(float,float)
MediaHandler : - ArrayList searchMedia(String,String,String,float)

Media : - String name
Media : - String genre
Media : - int rating

Series : ArrayList<ArrayList<int>> episodes

Movie : - int lengthOfMovie

Series : - int lengthOfEpisode(PLACEHOLDER)



@enduml